name : work-pull-request
on: 
  pull_request:
    branches:

jobs:
  build_and_test:
  runs-on: ubuntu-latest
  steps:
  - name: Validame el repositorio
    uses: actions/checkout@v2

  - name: Validar Python
    uses: actions/setup-python@v2
    with:
      python-version: "3.9.6"
      architecture: "x64"

  - name: Instalar librerias
    run: pip3 install - r requeriments.txt

  - name: Correr los Test
    run: python3 -m unittest -v